version: "3"
services:  
  auth0demo:
    build:
      dockerfile: ./dockerfile
      context: ./
    image: auth0demo
    ports:
    - "3000:3000"
    environment:    
    - AUTH0_CLIENT_ID={ClientID}
    - AUTH0_DOMAIN={Domain}
    - AUTH0_CLIENT_SECRET={Secret}
    - AUTH0_BASE_URL=http://localhost:3000
    - AUTH0_CALLBACK_URL=http://localhost:3000/callback
    restart: always